### ISSUE TITLE
ERROR: this R is version 4.0.4, package 'ESCO' requires R >= 4.1

### ISSUE THREAD

**Issue by JoelParkerUofA** [JINJINT/ESCO#2]
Hello, 
I am trying to download this package and I am getting the following error:

ERROR: this R is version 4.0.4, package 'ESCO' requires R >= 4.1

I have the most current version of R so I don't know how this could be possible. 

Thank you for your time.

**Comment by JINJINT** [comment]
Hi,

Sorry for this inconvenience, the requirement was made for submitting to
Bioconductor, and it is not necessary, so I have changed the requirement to
>=3.6. Hope this is fine now:) Thanks!

Best,
Jinjin

**Comment by JoelParkerUofA** [comment]
I am still getting the same error on two different computes. Thank you for your time and support on this.

**Comment by JINJINT** [comment]
Oh I forgot to push the changes ... Now it should be updated and ready to
go.

Let me know if you have further questions!

**Comment by JoelParkerUofA** [comment]
Looks good. Thank you for this.

**Comment by JINJINT** [comment]
No problem! Any time.
